/* bitwise
 *  and & 
 *  or |
 *  xor ^
 *  not ~
 *  shift <<, >>  0011 <<2 :- 1100 | 0011 >>2 :- 0000
 what is a shift register?
  hardware extends the no. of in pins on microcontroller
  requires 3 pins to controll
    clock data update pin
    clock generated by arduino
  74hc 595 shift register  
  
 
 */

 const int dataPin = 6;
 const int clockPin = 7;
 const int latchPin = 8;

 byte ledMap = 0b11110000;//byte specific to arduino single byte
 int delayTime = 3000;//ledMap 0b denotes binary num









void setup() {
  // set up pinModes
  pinMode(dataPin,OUTPUT);
  pinMode(clockPin,OUTPUT);
  pinMode(latchPin,OUTPUT);

  Serial.begin(9600);
  shiftWrite(0x00);//hex code 0 for all led
  Serial.println("Enter a number between 0-255");
  
}

void loop() {
  if(Serial.available())//if data in serial
  {
    int inputVal = Serial.parseInt();//parse the value

    if(inputVal > 255)//if more than 255
    {
      Serial.println("Uh oh, try again");
      Serial.println("Enter a number between 0-255");
      return;//top of the list
    }
    
    Serial.print("Decimal: ");
    Serial.println(inputVal);
    Serial.print("Bianry: ");
    Serial.println(inputVal,BIN);//prints binary num
    Serial.println();

    Serial.print("AND result: ");
    Serial.println(ledMap & inputVal,BIN);///ledMap a binary num
    shiftWrite(ledMap & inputVal);
    delay(delayTime);

    Serial.print("OR result: ");
    Serial.println(ledMap | inputVal,BIN);
    shiftWrite(ledMap & inputVal);
    delay(delayTime);

    Serial.print("XOR result: ");
    Serial.println(ledMap ^ inputVal,BIN);
    shiftWrite(ledMap & inputVal);
    delay(delayTime);

    
    Serial.println("Enter a number between 0-255");






    
  }

}
void shiftWrite(byte value)
{
  digitalWrite(latchPin, LOW);
  shiftOut(dataPin, clockPin, MSBFIRST, value);
  digitalWrite(latchPin,HIGH);
}
